sudo: required
dist: trusty

language: haxe

services:
  - redis-server

os:
  - linux
  - osx
  
haxe:
  - "3.2.1"
  - development
  
matrix:
  allow_failures:
    - haxe: development
    
install:
  - haxelib git extern-js https://github.com/ExternKit/extern-js
  - haxelib git travix https://github.com/back2dos/travix
  - haxelib run travix install

script:
  - haxelib run travix node
